env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always